#!/bin/bash

curl -s https://raw.githubusercontent.com/CodingCatAero/VaultHelper/main/vaultHelper | sudo tee /usr/local/bin/vaultHelper > /dev/null

mkdir "$HOME/.config/vaultHelper" > /dev/null

curl -s https://raw.githubusercontent.com/CodingCatAero/VaultHelper/refs/heads/main/Assets/vaultHelperIcon.png > "$HOME/.config/vaultHelper/vaultHelperIcon.png"