#!/bin/bash
checkFailure() {
    if [[ $1 == 0 ]] ;
    then
        printf "\nDone!"
    else
        printf "\nFailed..."
    fi
}

sudo printf ""

if [[ $? ]] ;
then
    printf "Downloading script to %s/.local/bin/" "$HOME"
    curl -s https://raw.githubusercontent.com/CodingCatAero/VaultHelper/refs/heads/main/vaultHelper | sudo tee "$HOME/.local/bin/vaultHelper" &> /dev/null
    checkFailure $?

    printf "\n\nCreating vaultHelper directory in %s/.config/" "$HOME"
    mkdir "$HOME/.config/vaultHelper" &> /dev/null
    checkFailure $?

    printf "\n\nDownloading icons to %s/.local/share/icons/hicolor" "$HOME"
    curl -s https://raw.githubusercontent.com/CodingCatAero/VaultHelper/refs/heads/main/Assets/iconPack.tar.gz > "$HOME/Downloads/iconPack.tar.gz"
    sudo tar -xf "$HOME/Downloads/iconPack.tar.gz"  --one-top-level=$HOME/.local/share/icons/hicolor
    rm "$HOME/Downloads/iconPack.tar.gz" &> /dev/null
    checkFailure $?

    printf "\n\nDownloading desktop file to %s/.local/share/applications/" "$HOME"
    curl -s https://raw.githubusercontent.com/CodingCatAero/VaultHelper/refs/heads/main/Assets/vaultHelper.desktop | sudo tee "$HOME/.local/share/applications/vaultHelper.desktop" &> /dev/null
    checkFailure $?

    printf "\n\nSetting read & executable permissions for the script and desktop file"
    sudo chmod 555 "$HOME/.local/bin/vaultHelper" && sudo chmod 555 "$HOME/.local/share/applications/vaultHelper.desktop"
    checkFailure $?

    printf "\n\nInstalled!!"
fi
