#!/bin/bash
checkFailure() {
    if [[ $1 == 0 ]] ;
    then
        printf "\nDone!"
    else
        printf "\nFailed..."
    fi
}

sudo printf ""

if [[ $? ]] ;
then
    printf "Downloading script to /usr/local/bin/"
    curl -s https://raw.githubusercontent.com/CodingCatAero/VaultHelper/refs/heads/main/vaultHelper | sudo tee /usr/local/bin/vaultHelper &> /dev/null
    checkFailure $?

    printf "\n\nCreating vaultHelper directory in %s/" "$HOME"
    mkdir "$HOME/.config/vaultHelper" &> /dev/null
    checkFailure $?

    printf "\n\nDownloading icons to /usr/share/icons/hicolor/"
    curl -s https://raw.githubusercontent.com/CodingCatAero/VaultHelper/refs/heads/main/Assets/iconPack.tar.gz > "$HOME/Downloads/iconPack.tar.gz"
    sudo tar -xf "$HOME/Downloads/iconPack.tar.gz"  --one-top-level=/usr/share/icons/hicolor
    rm "$HOME/Downloads/iconPack.tar.gz" &> /dev/null
    checkFailure $?

    printf "\n\nDownloading desktop file to %s/Desktop/" "$HOME"
    curl -s https://raw.githubusercontent.com/CodingCatAero/VaultHelper/refs/heads/main/Assets/vaultHelper.desktop | sudo tee "$HOME/Desktop/vaultHelper.desktop" &> /dev/null
    checkFailure $?

    printf "\n\nSetting read & executable permissions for the script and desktop file"
    sudo chmod 555 /usr/local/bin/vaultHelper && sudo chmod 555 "$HOME"/Desktop/vaultHelper.desktop
    checkFailure $?

    printf "\n\nInstalled!!"
fi