#!/bin/bash

if [[ $(sudo echo) ]] ;
then
    answers=("y" "yes" "Y" "Yes" "YES")

    read -r -p "Are you sure you want to uninstall? [y/N] " choice

    for option in "${answers[@]}" ;
    do
        if [[ $option == "$choice" ]] ;
        then
            choice=""
            read -r -p "Would you like to clear the config? [y/N] " choice

            if [[ $option == "$choice" ]] ;
            then
                rm -rf "$HOME/.config/vaultHelper"
            fi

            sudo rm -f /usr/local/bin/vaultHelper

            for dir in /usr/share/icons/hicolor/*/ ;
            do
                if [[ $dir =~ ([0-9]+)"x"([0-9]+)"/" ]] ;
                then
                    sudo rm "$dir"apps/vaultHelper.png
                fi
            done

            rm "$HOME/Desktop/vaultHelper.desktop"
        fi
    done
fi
